<?php
$productos = $this->productos;
$this->headTitle($this->titulo);
?>
<div class="page-header">
    <h1><?= $this->escapeHtml($this->titulo)?></h1>
</div>
<p>
    <a href="<?= $this->url('catalogo', ['action' => 'crear']) ?>" class="btn btn-default btn-xs">
        crear (+)
    </a>
</p>
<table class="table table-striped table-hover table-bordered">
    <thead>
    <tr>
        <th>Id</th>
        <th>Descripcion</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Opciones</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($productos as $producto) :?>
        <tr>
            <td><?=$producto->getId()?></td>
            <td><?=$producto->getDescripcion()?></td>
            <td><?=$producto->getPrecio()?></td>
            <td><?=$producto->getCantidad()?></td>
            <td>
                <a href="<?=$this->url('catalogo', ['action' =>'editar', 'id' => $producto->getId()])?>"
                   class="btn btn-warning btn-xs">Editar</a>
                <a href="<?=$this->url('catalogo', ['action' =>'eliminar', 'id' => $producto->getId()])?>"
                   onclick="return confirm('¿Esta seguro que desea eliminar a <?= $producto->getDescripcion() ?>?');"
                   class="btn btn-danger btn-xs">Eliminar</a>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>

