<div class="page-header">
    <h1><?= $this->titulo ?></h1>
</div>

<table class="table table-striped table-hover" style="width:700px;">
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Detalle</th>
    </tr>
    <?php foreach ($this->listaUsuario as $usuario): ?>
        <tr>
            <td><?=$usuario->getId()?></td>
            <td><?=$usuario->getNombre()?></td>
            <td><?=$usuario->getApellido()?></td>
            <td>
                <a href="<?= $this->url('index', ['action' => 'ver', 'id' => $usuario->getId()]) ?>">Ver</a>
            </td>
        </tr>

    <?php endforeach; ?>
</table>
