<div class="page-header">
    <h1><?= $this->titulo ?></h1>
</div>

<a href="<?= $this->basePath()?>/usuario/index" class="btn btn-default"> <= Atras</a>
<hr>
<?php if ($this->usuario !== null): ?>
    <p>
        <span><strong>Id:</strong></span>
        <?php echo $this->usuario->getId() ?>
    </p>
    <p>
        <span><strong>Nombre:</strong></span>
        <?php echo $this->usuario->getNombre() ?>
    </p>
    <p>
        <span><strong>Apellido:</strong></span>
        <?php echo $this->usuario->getApellido() ?>
    </p>
<?php else: ?>
    <h4>Usuario no encontrado</h4>
<?php endif; ?>